package com.pmgo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("t_pm_project", "id", PmProject.class);
		arp.addMapping("t_pm_requirement", "id", PmRequirement.class);
		arp.addMapping("t_sys_logs", "id", SysLogs.class);
		arp.addMapping("t_sys_system", "id", SysSystem.class);
		arp.addMapping("t_sys_user", "id", SysUser.class);
	}
}

