package com.pmgo.common.model;

import com.pmgo.common.model.base.BasePmProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmProject extends BasePmProject<PmProject> {
	public static final PmProject dao = new PmProject().dao();
}
