package com.pmgo.common.model;

import com.pmgo.common.model.base.BasePmRequirement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmRequirement extends BasePmRequirement<PmRequirement> {
	public static final PmRequirement dao = new PmRequirement().dao();
}
