package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseRelationProjectUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelationProjectUser extends BaseRelationProjectUser<RelationProjectUser> {
	public static final RelationProjectUser dao = new RelationProjectUser().dao();
}
