package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseRelationTaskUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelationTaskUser extends BaseRelationTaskUser<RelationTaskUser> {
	public static final RelationTaskUser dao = new RelationTaskUser().dao();
}
