package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseSysLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLogs extends BaseSysLogs<SysLogs> {
	public static final SysLogs dao = new SysLogs().dao();
}
