package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseSysSystem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSystem extends BaseSysSystem<SysSystem> {
	public static final SysSystem dao = new SysSystem().dao();
}
