package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseTesterBugs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TesterBugs extends BaseTesterBugs<TesterBugs> {
	public static final TesterBugs dao = new TesterBugs().dao();
}
