package com.pmgo.common.model;

import com.pmgo.common.model.base.BaseUserTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTask extends BaseUserTask<UserTask> {
	public static final UserTask dao = new UserTask().dao();
}
