package com.pmgo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePmProject<M extends BasePmProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setBegin(java.util.Date begin) {
		set("begin", begin);
		return (M)this;
	}

	public java.util.Date getBegin() {
		return get("begin");
	}

	public M setEng(java.util.Date eng) {
		set("eng", eng);
		return (M)this;
	}

	public java.util.Date getEng() {
		return get("eng");
	}

}
