package com.pmgo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserTask<M extends BaseUserTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setTimeBegin(java.util.Date timeBegin) {
		set("time_begin", timeBegin);
		return (M)this;
	}

	public java.util.Date getTimeBegin() {
		return get("time_begin");
	}

	public M setTimeEnd(java.util.Date timeEnd) {
		set("time_end", timeEnd);
		return (M)this;
	}

	public java.util.Date getTimeEnd() {
		return get("time_end");
	}

	public M setTimeAlarm(java.util.Date timeAlarm) {
		set("time_alarm", timeAlarm);
		return (M)this;
	}

	public java.util.Date getTimeAlarm() {
		return get("time_alarm");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public M setMem(java.lang.String mem) {
		set("mem", mem);
		return (M)this;
	}

	public java.lang.String getMem() {
		return get("mem");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.String getState() {
		return get("state");
	}

	public M setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
		return (M)this;
	}

	public java.lang.String getProjectId() {
		return get("project_id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

}
