package com.pmgo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTesterBugs<M extends BaseTesterBugs<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setPlatform(java.lang.String platform) {
		set("platform", platform);
		return (M)this;
	}

	public java.lang.String getPlatform() {
		return get("platform");
	}

	public M setPrecodition(java.lang.String precodition) {
		set("precodition", precodition);
		return (M)this;
	}

	public java.lang.String getPrecodition() {
		return get("precodition");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public M setDegree(java.lang.String degree) {
		set("degree", degree);
		return (M)this;
	}

	public java.lang.String getDegree() {
		return get("degree");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.String getState() {
		return get("state");
	}

	public M setPersonCommit(java.lang.String personCommit) {
		set("person_commit", personCommit);
		return (M)this;
	}

	public java.lang.String getPersonCommit() {
		return get("person_commit");
	}

	public M setPersonSolve(java.lang.String personSolve) {
		set("person_solve", personSolve);
		return (M)this;
	}

	public java.lang.String getPersonSolve() {
		return get("person_solve");
	}

	public M setMem(java.lang.String mem) {
		set("mem", mem);
		return (M)this;
	}

	public java.lang.String getMem() {
		return get("mem");
	}

}
